# Generated by Django 5.0.1 on 2024-01-21 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=80, verbose_name='ФИО')),
                ('birth', models.DateField(verbose_name='Дата рождения')),
                ('death', models.DateField(verbose_name='Дата смерти')),
                ('content', models.TextField(verbose_name='Краткое описание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Наименование')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Наименование')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Print',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('city', models.CharField(max_length=30, verbose_name='Город')),
                ('create_print', models.DateField(verbose_name='Дата основания')),
                ('content', models.TextField(verbose_name='Краткое описание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название')),
                ('content', models.TextField()),
                ('year', models.CharField(max_length=4, verbose_name='Год выпуска')),
                ('isbn', models.CharField(max_length=17, verbose_name='ISBN')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('authors', models.ManyToManyField(to='ReadTheCity.author')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ReadTheCity.genre', verbose_name='Жанр')),
                ('lang', models.ManyToManyField(to='ReadTheCity.language')),
                ('print', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ReadTheCity.print', verbose_name='Издательство')),
            ],
        ),
    ]
