# Generated by Django 5.0.1 on 2024-01-21 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReadTheCity', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name': 'Авторы', 'verbose_name_plural': 'Авторы'},
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': 'Книги', 'verbose_name_plural': 'Книги'},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'verbose_name': 'Жанры', 'verbose_name_plural': 'Жанры'},
        ),
        migrations.AlterModelOptions(
            name='language',
            options={'verbose_name': 'Языки', 'verbose_name_plural': 'Языки'},
        ),
        migrations.AlterModelOptions(
            name='print',
            options={'verbose_name': 'Издательства', 'verbose_name_plural': 'Издательства'},
        ),
        migrations.AlterField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(to='ReadTheCity.author', verbose_name='Авторы'),
        ),
        migrations.AlterField(
            model_name='book',
            name='content',
            field=models.TextField(verbose_name='Краткое содержание'),
        ),
        migrations.AlterField(
            model_name='book',
            name='lang',
            field=models.ManyToManyField(to='ReadTheCity.language', verbose_name='Языки'),
        ),
    ]
