# Generated by Django 5.0.1 on 2024-01-23 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReadTheCity', '0004_profile_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='death',
            field=models.DateField(blank=True, null=True, verbose_name='Дата смерти'),
        ),
    ]
