# Generated by Django 5.0.1 on 2024-01-23 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReadTheCity', '0005_alter_author_death'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='birth',
            field=models.DateField(null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='О себе'),
        ),
    ]
