# Generated by Django 5.0.1 on 2024-01-23 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReadTheCity', '0007_book_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='upload',
            field=models.IntegerField(default=0, verbose_name='Количество скачиваний'),
        ),
    ]
